---
- hosts: all
#  debugger: always
#  gather_facts: yes
  vars:
    ovirt_host_pw: "{{ lookup('env','OVIRT_PASSWORD') }}"
    ansible_user: root
    host_key_checking: false
  tasks:
  - debug:
      msg:
      - "Executing based on OVIRT_PASSWORD: {{ lookup('env', 'OVIRT_PASSWORD') }}"
      - "Executing based on ovirt_host_pw: {{ ovirt_host_pw }}"

  - lineinfile: dest=/etc/ssh/sshd_config
                regexp='^#?PasswordAuthentication'
                line='PasswordAuthentication yes'
  - service: name=sshd state=restarted
  - user:
      name: root
      password: "{{ ovirt_host_pw | password_hash('sha512') }}"
  - yum:
      name: https://resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm
